x=c(input$Time..minutes. [which(input$Maine=='Away')])
y=c(input$Time..minutes.[which(input$Maine=='Maine')])
hist(x,main="Runner's time:Away",xlim=range(0,180),ylim=range(0,1800))
hist(y,main="Runner's time:Maine",xlim=c(0,180),ylim=c(0,1800))
summary(x)

boxplot(x,y,names = c('Away', 'Maine'))

summary(x)
summary(y)
mean(x)
mean(y)
sd(x)
sd(y)
median(x)
median(y)
range(x)
range(y)
IQR(x)
IQR(y)