input=read.csv("C:/Users/nihar/OneDrive/Documents/Niharika_UTD/Fall_2022/Stats_for_DS/MiniProject2/roadrace.csv")
maine=c(input$Maine)
a=sum(c(maine=='Maine'))
b=sum(c(maine=='Away'))
barplot(c(a,b),main=c("Runners from Maine Vs Away"), names.arg=c("Maine", "Away"), ylab="Number of runners")
print("Maine Runners")
print(a)
print("Away Runners")
print(b)
print("Total Number of Runners")
print(a+b)