m=c(input$Age[which(input$Sex=='M')])
AgeMales=strtoi(m)
f=c(input$Age[which(input$Sex=='F')])
AgeFemale=strtoi(f)
boxplot(AgeMales,AgeFemale,names = c('Male Runners Age','Female Runners Age'))

summary(AgeMales)
summary(AgeFemale)
mean(AgeMales)
mean(AgeFemale)
median(AgeMales)
median(AgeFemale)
range(AgeMales)
range(AgeFemale)
sd(AgeMales)
sd(AgeFemale)
IQR(AgeMales)
IQR(AgeFemale)